### PR TITLE
navbar fix for rider

### LINKED ISSUE #5: BUG: Rider can see tabs in navbar they cant/shouldnt access
### Summary

A user with ONLY a rider role should not be able to see field relevant to other roles and only ride request should be available to them, but right now they can see a dropdown for `Shifts` and `Drivers Page`

### Expected Behavior

The user should only see the dropdown for `Ride Request`

### Current / Observed Behavior

image

### Steps to Reproduce

1. Log in as user with no roles
2. Get your role toggled by an admin to be a rider
3. View navbar

Implementation Todo:

- [ ] Edit `AppNavbar.js` and make sure that the tabs are not available to riders

### PR DESCRIPTION
**Pull request by adilahmed2**
I added functionality so that if we are logged in as a rider only we cannot see the shifts and drivers dropdown in the navbar. 
Screenshot 2024-05-21 at 5 12 12 PM
Screenshot 2024-05-21 at 5 17 17 PM
Closes #5

### CODE REVIEW

**Review by katelarrick — APPROVED** [review]
It looks like the correct changes were made to keep users with no roles from seeing dropdown menus that they shouldn't be able to see. Good work!

**Review by gracefeng05 — DISMISSED** [review]
LGTM

**Review by katelarrick — DISMISSED** [review]
It looks like the correct changes were made to keep users with no roles from seeing dropdown menus that they shouldn't be able to see. Good work!

File: frontend/src/main/components/Nav/AppNavbar.js [hunk 1]
```diff
@@ -89,15 +89,9 @@ export default function AppNavbar({ currentUser, systemInfo, doLogout, currentUr
...
               {
-                !hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && (
-                  <NavDropdown title="Shifts" id="appnavbar-shift-dropdown" data-testid="appnavbar-shift-dropdown" >
-                    <NavDropdown.Item data-testid="appnavbar-shift-dropdown-shifts" as={Link} to="/shift/">Shifts</NavDropdown.Item>
-                  </NavDropdown>
-                )
-              }
-              {
-                hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && (
+               !hasRole(currentUser, "ROLE_RIDER") && isParticipant(currentUser) && (
```
Comment (pconrad) [inline frontend/src/main/components/Nav/AppNavbar.js:94]:
```suggestion
               hasRole(currentUser, "ROLE_DRIVER") ||    hasRole(currentUser, "ROLE_ADMIN")   (
```

I wonder if this would be more clear

File: frontend/src/main/components/Nav/AppNavbar.js [hunk 2]
```diff
@@ -120,7 +114,7 @@ export default function AppNavbar({ currentUser, systemInfo, doLogout, currentUr
                 )
               }
               {
-                isParticipant(currentUser) && (
+                !hasRole(currentUser, "ROLE_RIDER") && isParticipant(currentUser) && (
```
Comment (pconrad) [inline frontend/src/main/components/Nav/AppNavbar.js:117]: same here...

**Review by pconrad — DISMISSED** [review]
LGTM, apart from a couple of small changes that might make the code easier to read.

**Review by aneeshtheplug — APPROVED** [review]
LGTM

File: frontend/src/main/components/Nav/AppNavbar.js (hunk 2 above)
Comment (pconrad) [reply frontend/src/main/components/Nav/AppNavbar.js:117]: Same here again... you marked it as resolved but didn't make the change?

File: frontend/src/main/components/Nav/AppNavbar.js (hunk 1 above)
Comment (pconrad) [reply frontend/src/main/components/Nav/AppNavbar.js:94]: Adil: you marked this as resolved, but you didn't take the suggestion.  Do you think the current code is more clear?  Yesterday you seemed to agree with me.

**Review by pconrad — CHANGES_REQUESTED** [review]

File: frontend/src/main/components/Nav/AppNavbar.js (hunk 2 above)
Comment (adilahmed2) [reply frontend/src/main/components/Nav/AppNavbar.js]: Sorry professor. The code we wrote earlier did not work and I was failing a lot of the tests because of it. I realized it is because of the fact that we have an AND statement but we need an OR between the two cases. I changed the code and submitted a new pr!

File: frontend/src/main/components/Nav/AppNavbar.js (hunk 1 above)
Comment (adilahmed2) [reply frontend/src/main/components/Nav/AppNavbar.js]: I left a comment addressing this issue in the previous requested change.

**Review by pconrad — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM
